swagger: '2.0'
host: 'localhost:3000'
basePath: '/'
apiPath: '/src/routes/postdata.ts'
info:
  title: "Backend Post project"
  version: '1.0.0'
  description: "Backend project capable of reading data from a feed"
  termsOfService: 'http://swagger.io/terms/'
tags:
  - name: Post
    description: The posts managing API
paths:
  /post:
    get:
      summary: Get all posts
      tags: [Post]
      responses:
        200:
          description: The list of the posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'src/schemas/Post.json'
        500:
          description: Server error
  /posts-filtered:
    get:
      summary: Get filtered posts
      tags: [Post]
      parameters:
        - in: query
          name: title
          type: string
          description: Title of the post
        - in: query
          name: items
          type: number
          description: Number of items
      responses:
        200:
          description: The list of the filtered posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'src/schemas/Post.json'
        404:
          description: No posts found
        500:
          description: Server error
definitions:
  Post:
    type: object
    required:
      - id
      - date
      - date_gmt
      - guid
      - modified
      - modified_gmt
      - slug
      - status
      - type
      - link
      - title
      - content
      - excerpt
      - author
      - featured_media
      - comment_status
      - ping_status
      - sticky
      - template
      - format
      - meta
      - categories
      - tags
      - _links
    properties:
      id:
        type: integer
      date:
        type: string
      date_gmt:
        type: string
      guid:
        type: object
        required:
          - rendered
        properties:
          rendered:
            type: string
      modified:
        type: string
      modified_gmt:
        type: string
      slug:
        type: string
      status:
        type: string
      type1:
        type: string
      link:
        type: string
      title:
        type: object
        required:
          - rendered
        properties:
          rendered:
            type: string
      content:
        type: object
        required:
          - rendered
          - protected
        properties:
          rendered:
            type: string
          protected:
            type: boolean
      excerpt:
        type: object
        required:
          - rendered
          - protected
        properties:
          rendered:
            type: string
          protected:
            type: boolean
      author:
        type: integer
      featured_media:
        type: integer
      comment_status:
        type: string
      ping_status:
        type: string
      sticky:
        type: boolean
      template:
        type: string
      format:
        type: string
      meta:
        type: object
        required:
          - inline_featured_image
          - footnotes
        properties:
          inline_featured_image:
            type: boolean
          footnotes:
            type: string
      categories:
        type: array
        items:
          type: integer
      tags:
        type: array
        items:
          type: integer
      _links:
        type: object
        required:
          - self
          - collection
          - about
          - author
          - replies
          - version-history
          - predecessor-version
          - 'wp:featuredmedia'
          - 'wp:attachment'
          - 'wp:term'
          - curies
        properties:
          self:
            type: array
            items:
              type: object
              required:
                - href
              properties:
                href:
                  type: string
          collection:
            type: array
            items:
              type: object
              required:
                - href
              properties:
                href:
                  type: string
          about:
            type: array
            items:
              type: object
              required:
                - href
              properties:
                href:
                  type: string
          author:
            type: array
            items:
              type: object
              required:
                - embeddable
                - href
              properties:
                embeddable:
                  type: boolean
                href:
                  type: string
          replies:
            type: array
            items:
              type: object
              required:
                - embeddable
                - href
              properties:
                embeddable:
                  type: boolean
                href:
                  type: string
          version-history:
            type: array
            items:
              type: object
              required:
                - embeddable
                - href
              properties:
                embeddable:
                  type: boolean
                href:
                  type: string
          predecessor-version:
            type: array
            items:
              type: object
              required:
                - embeddable
                - href
              properties:
                embeddable:
                  type: boolean
                href:
                  type: string
          'wp:featuredmedia':
            type: array
            items:
              type: object
              required:
                - embeddable
                - href
              properties:
                embeddable:
                  type: boolean
                href:
                  type: string
          'wp:attachment':
            type: array
            items:
              type: object
              required:
                - embeddable
                - href
              properties:
                embeddable:
                  type: boolean
                href:
                  type: string
          'wp:term':
            type: array
            items:
              type: object
              required:
                - taxonomy
                - embeddable
                - href
              properties:
                taxonomy:
                  type: string
                embeddable:
                  type: boolean
                href:
                  type: string
          curies:
            type: array
            items:
              type: object
              required:
                - name
                - href
                - rel
              properties:
                name:
                  type: string
                href:
                  type: string
                rel:
                  type: string
